name: test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: raviqqe/cargo-cache@6d2d8fbe4fc04627b0a05f603fce1dc9fd0baf0d # v1.0.0
      - run: cargo build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: raviqqe/cargo-cache@6d2d8fbe4fc04627b0a05f603fce1dc9fd0baf0d # v1.0.0
      - run: cargo test
